server:
  port: 8089

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test;AUTO_SERVER=TRUE
    username: sa
    password:

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
